[env]
TERM = "xterm-256color"

[colors.primary]
background = "#1d1f21"
foreground = "0xD8DEE9"

[colors.normal]
black = "0x191D24"
red = "0xBF616A"
green = "0xA3BE8C"
yellow = "0xEBCB8B"
blue = "0x81A1C1"
magenta = "0xB48EAD"
cyan = "0x8FBCBB"
white = "0xD8DEE9"

# [colors.cursor]
# text =  '#1d1f21'
# cursor = '#403d52'

[colors.bright]
black = "0x3B4252"
red = "0xD06F79"
green = "0xB1D196"
yellow = "0xF0D399"
blue = "0x88C0D0"
magenta = "0xC895BF"
cyan = "0x93CCDC"
white = "0xE5E9F0"

[colors.selection]
text = "0xD8DEE9"
background = "0x2E3440"

[font]
size = 12

[font.normal]
family = "NotoSansM Nerd Font Mono"
# family = "OverpassM Nerd Font Propo"
# family = "LiterationMonoPowerline Nerd Font" # 12.8
# family = "MesloLGL Nerd Font Mono"
# family = "IosevkaTerm Nerd Font Mono" # 13
style = "Medium"

  # [font.italic]
  # family = "NotoSansM Nerd Font Mono"
  # style = "Medium"

[window.padding]
y = 1
x = 2
